import type { GenerationTask } from "./types";

const now = Date.now();

export const seedTasks: GenerationTask[] = [
  {
    id: "t1",
    prompt: "Напиши пост для Telegram-канала о пользе утренних ритуалов, 300 слов, дружелюбный тон",
    model: "GPT-4o",
    type: "text",
    status: "running",
    progress: 42,
    error: null,
    credits: 3,
    eta: 18000,
    position: null,
    createdAt: now - 60000,
    completedAt: null,
  },
  {
    id: "t2",
    prompt: "Сгенерируй изображение: киберпанк-город на закате, неоновые вывески, дождь, 16:9",
    model: "DALL·E 3",
    type: "image",
    status: "running",
    progress: 18,
    error: null,
    credits: 5,
    eta: 25000,
    position: null,
    createdAt: now - 120000,
    completedAt: null,
  },
  {
    id: "t3",
    prompt: "Создай короткое видео: пролёт камеры над горным хребтом, cinematic, 10 секунд",
    model: "Kling 1.6",
    type: "video",
    status: "queued",
    progress: 0,
    error: null,
    credits: 15,
    eta: 90000,
    position: 1,
    createdAt: now - 30000,
    completedAt: null,
  },
  {
    id: "t4",
    prompt: "Сгенерируй фоновую музыку для медитации: спокойная, ambient, 3 минуты",
    model: "Suno v4",
    type: "audio",
    status: "queued",
    progress: 0,
    error: null,
    credits: 12,
    eta: 75000,
    position: 2,
    createdAt: now - 20000,
    completedAt: null,
  },
  {
    id: "t5",
    prompt: "Переведи текст договора с английского на русский, юридический стиль",
    model: "Claude 3.5 Sonnet",
    type: "text",
    status: "queued",
    progress: 0,
    error: null,
    credits: 2,
    eta: 12000,
    position: 3,
    createdAt: now - 10000,
    completedAt: null,
  },
  {
    id: "t6",
    prompt: "Иконка для мобильного приложения: минимализм, градиент, тема продуктивности",
    model: "Midjourney v6",
    type: "image",
    status: "done",
    progress: 100,
    error: null,
    credits: 5,
    eta: 0,
    position: null,
    createdAt: now - 300000,
    completedAt: now - 240000,
  },
  {
    id: "t7",
    prompt: "Создай лендинг для стартапа: структура, тексты, SEO-оптимизация",
    model: "GPT-4o",
    type: "text",
    status: "done",
    progress: 100,
    error: null,
    credits: 4,
    eta: 0,
    position: null,
    createdAt: now - 600000,
    completedAt: now - 540000,
  },
  {
    id: "t8",
    prompt: "Сгенерируй 3D-модель персонажа для игры: стилизованный, low-poly",
    model: "Meshy 4",
    type: "image",
    status: "failed",
    progress: 67,
    error: "Недостаточно кредитов для завершения генерации",
    credits: 8,
    eta: 0,
    position: null,
    createdAt: now - 180000,
    completedAt: now - 120000,
  },
  {
    id: "t9",
    prompt: "Сгенерируй озвучку для видео: мужской голос, деловой тон, русский язык, 2 минуты",
    model: "ElevenLabs",
    type: "audio",
    status: "queued",
    progress: 0,
    error: null,
    credits: 10,
    eta: 60000,
    position: 4,
    createdAt: now - 5000,
    completedAt: null,
  },
  {
    id: "t10",
    prompt: "Напиши SQL-запрос для аналитики продаж за последний квартал с группировкой по категориям",
    model: "Claude 3.5 Sonnet",
    type: "text",
    status: "done",
    progress: 100,
    error: null,
    credits: 1,
    eta: 0,
    position: null,
    createdAt: now - 900000,
    completedAt: now - 870000,
  },
];
